"""empty message

Revision ID: 227e4748b54f
Revises: 40485e49dfaa
Create Date: 2015-10-14 20:12:34.506633

"""

# revision identifiers, used by Alembic.
revision = '227e4748b54f'
down_revision = '40485e49dfaa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_user',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('user_lock',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('lock_id', sa.Integer(), nullable=True),
    sa.Column('is_owner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['lock_id'], ['lock.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('roles_users')
    op.add_column(u'user', sa.Column('first_name', sa.String(length=255), nullable=True))
    op.add_column(u'user', sa.Column('last_name', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'user', ['first_name'])
    op.create_unique_constraint(None, 'user', ['last_name'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column(u'user', 'last_name')
    op.drop_column(u'user', 'first_name')
    op.create_table('roles_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], name=u'roles_users_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'roles_users_user_id_fkey')
    )
    op.drop_table('user_lock')
    op.drop_table('role_user')
    op.drop_table('lock')
    ### end Alembic commands ###
