"""empty message

Revision ID: 1a5c8d9c75a6
Revises: 227e4748b54f
Create Date: 2015-10-16 15:01:53.720461

"""

# revision identifiers, used by Alembic.
revision = '1a5c8d9c75a6'
down_revision = '227e4748b54f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock', sa.Column('owner', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'lock', ['owner'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lock', type_='unique')
    op.drop_column('lock', 'owner')
    ### end Alembic commands ###
