"""empty message

Revision ID: 22a633e3d851
Revises: 448b2618f5d3
Create Date: 2015-11-03 19:40:34.675981

"""

# revision identifiers, used by Alembic.
revision = '22a633e3d851'
down_revision = '448b2618f5d3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock', sa.Column('name', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lock', 'name')
    ### end Alembic commands ###
