"""empty message

Revision ID: 28c55ef8d806
Revises: 3c4e5b7d7e80
Create Date: 2015-11-17 17:33:58.554638

"""

# revision identifiers, used by Alembic.
revision = '28c55ef8d806'
down_revision = '3c4e5b7d7e80'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock', sa.Column('actually_open', sa.Boolean(), nullable=True))
    op.drop_column('lock', 'last_opened')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock', sa.Column('last_opened', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('lock', 'actually_open')
    ### end Alembic commands ###
