"""empty message

Revision ID: 34431ad060db
Revises: 22a633e3d851
Create Date: 2015-11-04 19:24:31.431044

"""

# revision identifiers, used by Alembic.
revision = '34431ad060db'
down_revision = '22a633e3d851'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'friend_id')
    )
    op.add_column(u'user_lock', sa.Column('expiry', sa.DATE(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user_lock', 'expiry')
    op.drop_table('friend')
    ### end Alembic commands ###
