"""empty message

Revision ID: 3bf61d49aa5a
Revises: 42da6d7ec75b
Create Date: 2015-11-03 12:53:53.043514

"""

# revision identifiers, used by Alembic.
revision = '3bf61d49aa5a'
down_revision = '42da6d7ec75b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'lock_owner_key', 'lock', type_='unique')
    op.drop_column('lock', 'owner')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock', sa.Column('owner', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_unique_constraint(u'lock_owner_key', 'lock', ['owner'])
    ### end Alembic commands ###
