"""empty message

Revision ID: 3c4e5b7d7e80
Revises: 3c1107bed5e9
Create Date: 2015-11-17 17:16:57.423398

"""

# revision identifiers, used by Alembic.
revision = '3c4e5b7d7e80'
down_revision = '3c1107bed5e9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock', sa.Column('last_opened', sa.DateTime(), nullable=True))
    op.add_column('lock', sa.Column('requested_open', sa.Boolean(), nullable=True))
    op.drop_column('lock', 'locked')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lock', sa.Column('locked', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('lock', 'requested_open')
    op.drop_column('lock', 'last_opened')
    ### end Alembic commands ###
